2022-10-13 03:38:53,630 - distributed.worker - WARNING - Compute Failed
Key:       execute_one_subtree-848fee539b28e4d61eb029cb7f028735
Function:  execute_one_subtree
args:      (<forms.executor.executionnode.FunctionExecutionNode object at 0x7f1431c53220>)
kwargs:    {}
Exception: 'AssertionError()'

Distributing data time: 0.8581926822662354
Execution time: 0.15271615982055664
Traceback (most recent call last):
  File "/home/ubuntu/forms/benchmark/test_driver.py", line 50, in <module>
    result = fs.compute_formula(df, formula_str)
  File "/home/ubuntu/forms/forms/core/forms.py", line 44, in compute_formula
    res = plan_executor.df_execute_formula_plan(df, root)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/planexecutor.py", line 81, in df_execute_formula_plan
    return res_table.get_table_content()
  File "/home/ubuntu/forms/forms/executor/table.py", line 55, in get_table_content
    self.df = self.remote_df.get_df_content()
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 80, in get_df_content
    [
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 82, in <listcomp>
    [one_partition.remote_obj.get_computed_result() for one_partition in one_row],
  File "/home/ubuntu/forms/forms/executor/dfexecutor/remotedf.py", line 82, in <listcomp>
    [one_partition.remote_obj.get_computed_result() for one_partition in one_row],
  File "/home/ubuntu/forms/forms/runtime/remoteobject.py", line 33, in get_computed_result
    return self.object_ref.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/distributed/client.py", line 277, in result
    raise exc.with_traceback(tb)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/planexecutor.py", line 45, in execute_one_subtree
    res_table = function_executor(physical_subtree)
  File "/home/ubuntu/forms/forms/executor/dfexecutor/basicfuncexecutor.py", line 187, in sumif_df_executor
    assert op in operator_dict.keys()
AssertionError
